{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "voidllm.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voidllm.fullname" . }}
  labels:
    {{- include "voidllm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.adminKey }}
  VOIDLLM_ADMIN_KEY: {{ .Values.secrets.adminKey | b64enc | quote }}
  {{- else if and $existing $existing.data (index $existing.data "VOIDLLM_ADMIN_KEY") }}
  VOIDLLM_ADMIN_KEY: {{ index $existing.data "VOIDLLM_ADMIN_KEY" }}
  {{- else }}
  VOIDLLM_ADMIN_KEY: {{ randAlphaNum 48 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.encryptionKey }}
  VOIDLLM_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  {{- else if and $existing $existing.data (index $existing.data "VOIDLLM_ENCRYPTION_KEY") }}
  VOIDLLM_ENCRYPTION_KEY: {{ index $existing.data "VOIDLLM_ENCRYPTION_KEY" }}
  {{- else }}
  VOIDLLM_ENCRYPTION_KEY: {{ randBytes 32 | b64enc | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.license }}
  VOIDLLM_LICENSE: {{ .Values.secrets.license | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.ssoClientSecret }}
  VOIDLLM_SSO_CLIENT_SECRET: {{ .Values.secrets.ssoClientSecret | b64enc | quote }}
  {{- end }}
  {{- range $key, $val := .Values.secrets.extraEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
